---
control:
    hosts:
      ubuntu-c:
        hosts:
          10.0.3.40:
      ubuntu1:
        hosts: 
          10.0.3.58:
        ansible_user: packt
centos:
    hosts:
      centos1:
        hosts: 
          10.0.3.178:
        ansible_user: root
        ansible_port: 2222
...
