---
-
  # Target:
  hosts: all
  
  # Task:
  # can also be used for pre and post tasks
  tasks:
    - name: Jinja2 Template
      template:
        src: template.j2
        dest: "/tmp/{{ansible_hostname}}_template.out"
        trim_blocks: true

...
