[all]

[centos1]
10.0.3.178 ansible_user=root ansible_port=2222

[centos2]
10.0.3.87 ansible_user=root

[centos3]
10.0.3.155 ansible_user=root

[ubuntu-c]
10.0.3.40 ansible_user=packt ansible_become=true ansible_become_pass=password

[ubuntu1]
10.0.3.58 ansible_user=packt ansible_become=true ansible_become_pass=password

[ubuntu2]
10.0.3.218 ansible_user=packt ansible_become=true ansible_become_pass=password

[ubuntu3]
10.0.3.152 ansible_user=packt ansible_become=true ansible_become_pass=password
