---
control:
  hosts:
    vagrant:
      ansible_port: 10.0.2.15
      ansible_connection: local
    ubuntu-c:
      ansible_port: 10.0.3.40
    ubuntu1:
      ansible_port: 10.0.3.58
  vars:
    ansible_user: packt
    ansible_become: true
    ansible_become_pass: password
...
