---

# PLAY1
-

  # Target: 
  hosts: all

  # Task: the list of tasks that will be executed within the play, this section
  # can also be used for pre and post tasks
  tasks:
    - name: Create group based on ansible_distribution
      group_by:
        key: "custom_{{ ansible_distribution | lower }}"

# PLAY2
-

  # Target: where our play will run and options it will run with
  hosts: custom_centos

  # Task: the list of tasks that will be executed within the play, this section
  # can also be used for pre and post tasks
  tasks:
    - name: Ping all in custom_centos
      ping:

# Three dots indicate the end of a YAML document
...

